sonar.projectKey=thomasrincon2021-creator_taller_calidad_software_Thomas_Rincon
sonar.organization=thomasrincon2021-creator

sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=build/classes/java/main

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.sourceEncoding=UTF-8