# Configuración del Puerto del Servidor Backend
server.port=8080

# Conexión a la Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_modulo_productos?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# === LÍMITE DE TAMAÑO PARA IMÁGENES EN BASE64 ===
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
server.tomcat.max-http-form-post-size=8MB

# === CONFIGURACIÓN DE CORREO SMTP (GMAIL) ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Desactivar la verificación estricta de certificados SSL
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# === CONFIGURACIÓN DE MERCADO PAGO ===
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:}